openapi: "3.0.1"
info:
  title: IntegrationTypeCompDemo
  version: "1.0"
paths:
  /aws_proxy:
    get:
      responses:
        200:
          description: 200 response
          content: {}
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${IntegrationTypeCompDemoFunction.Arn}/invocations
        responses:
          default:
            statusCode: "200"
        type: aws_proxy
