AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 3

Resources:
  AnyResponseCodeByAwsProxyDemoApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: v1
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: swagger.yaml

  AnyResponseCodeByAwsProxyDemoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/
      Handler: app.lambda_handler
      Runtime: python2.7
      Events:
        AnyResponseCodeByAwsProxyDemo:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId: !Ref AnyResponseCodeByAwsProxyDemoApi

Outputs:
  InvokeUrl:
    Value: !Sub "https://${AnyResponseCodeByAwsProxyDemoApi}.execute-api.${AWS::Region}.amazonaws.com/v1/"
